### ISSUE TITLE
too many open file error 

### ISSUE THREAD

**Issue by LGG02** [google/deeppolisher#3]
Hi,

I am following the commands from case study and encountered below error in the `inference` command:
Traceback (most recent call last):
  File "/opt/conda/envs/bio/bin/polisher", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/polisher/cli.py", line 109, in run
    app.run(main, flags_parser=parse_flags)
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/polisher/cli.py", line 105, in main
    app.run(inference.main, argv=passed)
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/polisher/inference/inference.py", line 361, in main
    setup_inference(
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/polisher/inference/inference.py", line 332, in setup_inference
    run_inference(
  File "/opt/conda/envs/bio/lib/python3.9/site-packages/polisher/inference/inference.py", line 248, in run_inference
    with multiprocessing.Pool(processes=_CPUS.value) as pool:
  File "/opt/conda/envs/bio/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/opt/conda/envs/bio/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/opt/conda/envs/bio/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/opt/conda/envs/bio/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/opt/conda/envs/bio/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/conda/envs/bio/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/opt/conda/envs/bio/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/envs/bio/lib/python3.9/multiprocessing/popen_fork.py", line 65, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files

I have attached the complete log file. Shall I change the file limit using `ulimit`? I am working on a human genome 
[inference_log.txt](https://github.com/google/deeppolisher/files/15427610/inference_log.txt)

**Comment by kishwarshafin** [comment]
Hi @LGG02 ,

So sorry that this issue fell through the cracks. Are you still facing this issue?
